# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
