# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0003_quote_quoted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='favourites',
            new_name='favouriting_users',
        ),
    ]
